version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_DB: $APP_ENVIRONMENT
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_SECRET
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
